TrajectoryPlannerROS:
    controller_frequency: 7


    min_in_place_vel_theta: -0.2
    max_vel_x: 0.75
    min_vel_x: 0.1
    max_vel_theta: 1.0

    acc_lim_theta: 2.7
    acc_lim_x: 2.5
    acc_lim_y: 0

    sim_time: 5
    vx_samples: 20
    vtheta_samples: 40

    holonomic_robot: false

    yaw_goal_tolerence: 0.2
    xy_goal_tolerence: 0.1

    oscillation_reset_dist: 0.5


